name: CICD-EKS-Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read

    steps:
    # 1. Checkout source
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2. Configure AWS credentials (OIDC - No long-lived keys)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
        aws-region: us-west-1

    # 3. Terraform Init / Fmt / Validate / Plan / Apply
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve tfplan

    # 4. Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 5. Build & Push Docker Image
    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ${{ env.ECR_REPO_NAME }}:$IMAGE_TAG .

    - name: Tag image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker tag ${{ env.ECR_REPO_NAME }}:$IMAGE_TAG \
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG

    - name: Push image to ECR
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG

    # --------------------------
    # 6. Deploy to EKS
    # --------------------------
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml

